import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  // convert-units (and its lodash deps) expect Node's `global`.
  define: {
    global: 'globalThis',
  },
  plugins: [
    react(),
    VitePWA({
      registerType: 'prompt',
      // Generated by `bunx pwa-assets-generator` (see pwa-assets.config.ts) from
      // public/favicon.svg — swap the source SVG for real branding, then re-run it.
      includeAssets: [
        'favicon.svg',
        'favicon.ico',
        'apple-touch-icon-180x180.png',
        'fonts/*.woff2',
      ],
      manifest: {
        name: 'Family Menu Planner',
        short_name: 'MenuPlanner',
        description: 'Plan meals, weekly menus, and grocery lists — works offline.',
        theme_color: '#cf6139',
        background_color: '#fff7f1',
        display: 'standalone',
        start_url: '.',
        scope: '.',
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
      },
      devOptions: {
        enabled: false,
      },
    }),
  ],
})
