import type { MessageId } from './messages'
import type { PluralId } from './plurals'
import type { PluralForms } from './plurals'

export const ruMessages = {
  'app.title': 'Семейный планировщик меню',
  'nav.plan': 'План',
  'nav.groceries': 'Покупки',
  'nav.recipes': 'Рецепты',
  'nav.settings': 'Настройки',
  'action.back': 'Назад',
  'action.save': 'Сохранить',
  'action.cancel': 'Отмена',
  'action.delete': 'Удалить',
  'action.add': 'Добавить',
  'action.apply': 'Применить',
  'action.clear': 'Очистить',
  'action.close': 'Закрыть',
  'action.ok': 'ОК',
  'action.view': 'Открыть',
  'action.edit': 'Изменить',
  'action.rename': 'Переименовать',
  'action.remove': 'Убрать',
  'common.loading': 'Загрузка…',
  'common.name': 'Название',
  'common.none': 'Нет',
  'common.unknownItem': 'Неизвестный элемент',
  'common.unavailableTag': 'Недоступный тег',
  'common.unavailableIngredient': 'Недоступный ингредиент',
  'common.amount': 'Количество',
  'common.unit': 'Единица',
  'common.label': 'Название',
  'ingredient.usuallyAtHome': 'Обычно есть дома — отмечается на новых списках покупок',
  'ingredient.usuallyAtHomeShort': 'Обычно есть дома',
  'slot.eatingOut': 'Едим вне дома',
  'slot.notPlanned': 'Не запланировано',
  'slot.addDish': 'Добавить блюдо',
  'generation.generate': 'Подобрать',
  'generation.previewTitle': 'Предложение',
  'generation.previewBody': '{name} на {meal}, порции: {quantity}.',
  'generation.applied': 'Блюдо добавлено',
  'generation.noEligible': 'Нет полных блюд для этого приёма пищи.',
  'generation.slotNotEmpty': 'На этот приём уже есть блюдо.',
  'generation.slotExcluded': 'Этот приём исключён.',
  'generation.stale': 'План или рецепты изменились. Подберите снова.',
  'generation.weekGenerate': 'Подобрать меню',
  'generation.weekTitle': 'Подобрать меню',
  'generation.selectSlots': 'Выберите пустые приёмы. Заполненные и исключённые не изменятся.',
  'generation.noEmptySlots': 'На этой неделе нет пустых приёмов.',
  'generation.customAmount': 'Свои порции',
  'generation.running': 'Подбор…',
  'generation.unfilledRow': 'Нет полного блюда для: {meal}.',
  'generation.searchIncompleteRow':
    'Подбор остановился по лимиту времени до заполнения: {meal}. Это не значит, что неделю нельзя составить.',
  'generation.searchBudgetExhausted':
    'Подбор использовал {used} из {budget} расширений и оставил часть приёмов пустыми.',
  'generation.weekApplied': 'Блюда добавлены',
  'generation.diagnosticsTitle': 'Почему часть приёмов осталась пустой',
  'generation.dropCount': '{count} рецептов не подошли для {meal}: {reason}.',
  'generation.fixedConflictHelp': 'Уже запланированные приёмы не меняются:',
  'generation.fixedConflict': '{date} {meal}: {reasons}.',
  'generation.reason.not-complete': 'не полное блюдо',
  'generation.reason.occasion': 'другой приём пищи',
  'generation.reason.excluded-recipe': 'исключённый рецепт',
  'generation.reason.required-tags': 'нет нужной метки',
  'generation.reason.excluded-tags': 'есть исключённая метка',
  'generation.reason.include-ingredients': 'нет нужного ингредиента',
  'generation.reason.exclude-ingredients': 'есть исключённый ингредиент',
  'generation.reason.max-total-time': 'дольше лимита времени',
  'generation.reason.unknown-time': 'нет записанного времени',
  'generation.reason.unknown-ingredients': 'есть непривязанные строки ингредиентов',
  'generation.score.quick-day': 'Предпочтительно в день быстрых блюд.',
  'generation.score.effort': 'Меньше усилий среди допустимых вариантов.',
  'generation.score.repetition': 'Не повторяет блюдо, уже стоящее на этой неделе.',
  'generation.score.planned-history':
    'Не повторяет блюдо из плана прошлой недели (это план, а не подтверждённая готовка).',
  'generation.score.workload': 'Держит заготовку в пределах лимита семьи.',
  'generation.score.vegetable': 'Подходит под предпочтение овощей.',
  'generation.score.preferred-tags': 'Есть предпочтительная метка для подбора.',
  'generation.score.preferred-prep-day': 'Попадает на предпочтительный день заготовки.',
  'slot.noSlot': 'Нет слота',
  'slot.actions': 'Действия со слотом',
  'slot.includeAgain': 'Вернуть в план',
  'slot.editMeal': 'Изменить приём пищи',
  'slot.excludeEatingOut': 'Исключить / едим вне дома',
  'pwa.offlineReady': 'Приложение готово работать без сети.',
  'pwa.updateAvailable': 'Доступно обновление.',
  'pwa.reloadWhenReady': 'Обновить, когда будете готовы',
  'photo.unavailable': 'Фото недоступно без сети',
  'empty.recipes': 'Пока нет рецептов и простых блюд.',
  'empty.recipesHint':
    'Добавьте рецепт или импортируйте файл. Стартовый набор появляется только в пустой библиотеке.',
  'empty.listsOpen': 'Нет открытых списков. Создайте список из Плана.',
  'empty.listsClosed': 'Закрытых списков пока нет.',
  'empty.ingredients': 'Ингредиентов пока нет.',
  'empty.simpleFoods': 'Простых блюд пока нет.',
  'empty.groceryItems': 'Позиций пока нет.',
  'empty.allChecked': 'Все позиции отмечены.',
  'empty.noFilterMatch': 'Нет блюд по выбранным фильтрам.',
  'empty.cleanupNone': 'Пропусков по этому признаку нет.',
  'grocery.updateTitle': 'Обновить по плану',
  'grocery.updateLinked': 'С этим планом связан открытый список:',
  'grocery.updatePlanChanged': 'План изменился с момента создания списка.',
  'grocery.updateAdded': 'Добавлено',
  'grocery.updateChanged': 'Изменено',
  'grocery.updateRemoved': 'Больше не нужно по плану',
  'grocery.updateOverrides': 'Количество, которое вы правили',
  'grocery.updateWillUncheck': 'Будет снята отметка (количество выросло)',
  'grocery.updateManualKept': 'Ручные позиции останутся.',
  'grocery.updateNoLineDiffs':
    'Сгенерированные строки совпадают с планом. Обновление только освежит источники и ревизию плана.',
  'grocery.updateKeepQuantity': 'Оставить моё количество',
  'grocery.updateUsePlanned': 'Взять количество из плана',
  'grocery.updateExisting': 'Обновить существующий',
  'grocery.createNew': 'Создать новый',
  'grocery.updateCancel': 'Отмена',
  'grocery.updated': 'Список покупок обновлён',
  'grocery.generateFailed': 'Не удалось создать список ({error})',
  'grocery.created': 'Список покупок создан',
  'grocery.generate': 'Составить покупки',
  'grocery.updateFailed': 'Не удалось обновить список ({error})',
  'quantity.unspecified': 'количество не указано',
  'quantity.left': 'осталось',
  'quantity.remaining': 'остаток',
  'settings.language': 'Язык интерфейса',
  'settings.measurement': 'Отображение мер',
  'settings.measurementAsEntered': 'Как введено',
  'settings.measurementMetric': 'Метрическая (г/кг, мл/л)',
  'settings.measurementUs': 'Американская (унции, жидк. унции, чашки)',
  'settings.measurementHelp':
    'Меняется только отображение совместимых единиц. Сохранённые рецепты, чашки и планы не меняются.',
  'settings.backupPhotos':
    'В резервной копии есть адреса фото, но не сами файлы. Без сети вместо недоступных фото — заглушка.',
  'settings.title': 'Настройки',
  'settings.sectionDisplay': 'Отображение',
  'settings.sectionHousehold': 'Семья',
  'settings.sectionPrefs': 'Предпочтения по еде',
  'settings.sectionGeneration': 'Правила подбора',
  'settings.sectionBackup': 'Резервная копия',
  'settings.householdSize': 'Размер семьи',
  'settings.weekStartsOn': 'Неделя начинается',
  'settings.maxBatchPrep': 'Максимум единиц заготовки',
  'settings.maxBatchPrepHelp': 'Шаг 0,5. Два блюда за одну сессию — это 1,5.',
  'settings.preferredPrepDays': 'Предпочтительные дни заготовки',
  'settings.quickMealsDays': 'Дни только быстрых блюд',
  'settings.avoidDemanding': 'Не ставить несколько сложных заготовок на один день',
  'settings.favorVegetables': 'Стараться есть овощи каждый день',
  'settings.generationPreferredTags': 'Предпочтительные метки для подбора',
  'settings.generationPreferredTagsHelp':
    'Только мягкое предпочтение. Рецепты с хотя бы одной меткой ранжируются выше; это не обязательное условие.',
  'settings.generationHelp':
    'Жёсткие ограничения для «Подобрать меню». Без записанного времени или с непривязанными ингредиентами блюдо не подходит, пока вы не разрешите неизвестные данные. Удалённые идентификаторы остаются в списке и продолжают ограничивать.',
  'settings.excludedRecipes': 'Не предлагать эти рецепты',
  'settings.requiredTags': 'Должна быть хотя бы одна из этих меток',
  'settings.excludedTags': 'Исключить рецепты с этими метками',
  'settings.includeIngredients': 'Должен быть хотя бы один из этих ингредиентов',
  'settings.excludeIngredients': 'Исключить рецепты с этими ингредиентами',
  'settings.maxTotalTime': 'Максимум записанного общего времени (минуты)',
  'settings.maxTotalTimeHelp':
    'Пустое поле — без лимита. Если времени нет, действует правило для неизвестного времени.',
  'settings.unknownTime': 'Рецепты без записанного времени',
  'settings.unknownIngredients': 'Рецепты с непривязанными строками ингредиентов',
  'settings.unknownExclude': 'Не предлагать',
  'settings.unknownAllow': 'Разрешить',
  'settings.searchBudgetHelp':
    'Эти значения ограничивают объём работы «Подобрать меню», а не качество рецептов. Уменьшите их, чтобы остановиться раньше; это не второй набор кулинарных правил.',
  'settings.beamWidth': 'Ширина луча поиска',
  'settings.perSlotCandidateLimit': 'Кандидатов на один приём пищи',
  'settings.expansionBudget': 'Максимум расширений поиска',
  'settings.missingGenerationRefs':
    'Нет в этой библиотеке — ограничение сохраняется: рецепты {recipes}, метки {tags}, ингредиенты {ingredients}.',
  'settings.backupMissingGenerationRefs':
    'Правила подбора ссылаются на отсутствующие идентификаторы (сохранены, не удалены): рецепты {recipes}, метки {tags}, ингредиенты {ingredients}.',
  'settings.saved': 'Настройки сохранены',
  'settings.backupHelp':
    'Экспортируйте файл или восстановите его. Сначала показывается содержимое; замена данных — только после подтверждения.',
  'settings.exportBackup': 'Экспортировать копию',
  'settings.restoreBackup': 'Восстановить из копии',
  'settings.backupExported': 'Копия экспортирована',
  'settings.restoreTitle': 'Восстановить эту копию?',
  'settings.restoreReplaceHelp': 'Это заменит данные на этом устройстве.',
  'settings.exportCurrent': 'Экспортировать текущие данные',
  'settings.replaceRestore': 'Заменить и восстановить',
  'settings.restoredTitle': 'Копия восстановлена',
  'settings.restoredBody': 'На этом устройстве теперь данные из копии.',
  'settings.invalidJson': 'Этот файл не является корректным JSON',
  'settings.backupFormatOk': 'Формат копии: поддерживается',
  'settings.backupRecipes': 'Рецепты: {count}',
  'settings.backupFoods': 'Простые блюда: {count}',
  'settings.backupPlans': 'Планы: {count}',
  'settings.backupLists': 'Списки покупок: {count}',
  'settings.backupExportedAt': 'Экспортировано: {when}',
  'backup.error.invalid': 'Это не корректная копия PlanEat. Данные на устройстве не изменены.',
  'backup.error.writeFailed': 'Не удалось восстановить копию: локальные данные не изменены.',
  'backup.error.unsupportedVersion':
    'Эта копия использует формат версии {found}. Приложение поддерживает версию {supported}. Данные на устройстве не изменены.',
  'week.this': 'Эта неделя',
  'week.last': 'Прошлая неделя',
  'week.next': 'Следующая неделя',
  'week.prev': 'Предыдущая неделя',
  'week.nextNav': 'Следующая неделя',
  'week.calendar': 'Календарь недель',
  'week.history': 'Прошлая неделя',
  'month.prev': 'Предыдущий месяц',
  'month.next': 'Следующий месяц',
  'plan.title': 'План',
  'plan.loading': 'Загрузка плана…',
  'plan.loadFailed': 'Не удалось загрузить план недели.',
  'plan.createFailed': 'Не удалось создать план недели',
  'plan.unexcludeFailed': 'Не удалось вернуть этот приём пищи',
  'plan.openFailed': 'Не удалось открыть эту неделю',
  'plan.dayPlanned': 'запланирован',
  'plan.dayEmpty': 'пусто',
  'plan.sameDayOnly': 'только в день готовки',
  'plan.sameDayTooltip':
    'Это блюдо нужно съесть в день готовки. Остаток нельзя перенести на другой день.',
  'plan.prepUnits': 'Заготовка · {units}',
  'plan.backToWeek': 'Неделя',
  'plan.gridMeals': 'Приёмы',
  'plan.leftover': 'Остаток',
  'plan.wontCarryOver': 'Не переносится',
  'mealType.breakfast': 'Завтрак',
  'mealType.lunch': 'Обед',
  'mealType.dinner': 'Ужин',
  'role.complete': 'Полное блюдо (можно выбрать отдельно)',
  'role.main': 'Основное',
  'role.side': 'Гарнир',
  'role.vegetable': 'Овощное дополнение',
  'role.breakfast-component': 'Компонент завтрака',
  'roleChip.complete': 'Полное',
  'roleChip.main': 'Основное',
  'roleChip.side': 'Гарнир',
  'roleChip.vegetable': 'Овощи',
  'roleChip.breakfast-component': 'К завтраку',
  'effort.quick': 'Быстро',
  'effort.regular': 'Обычное',
  'effort.demanding': 'Сложное',
  'reuse.fresh-only': 'Только свежее',
  'reuse.same-day': 'В тот же день',
  'reuse.batch-friendly': 'Можно заготовить',
  'dishType.soup': 'Суп',
  'dishType.salad': 'Салат',
  'dishType.stew': 'Рагу',
  'dishType.casserole': 'Запеканка',
  'dishType.pasta': 'Паста',
  'dishType.roast': 'Жаркое',
  'dishType.grill': 'Гриль',
  'dishType.sandwich': 'Сэндвич',
  'dishType.baked-good': 'Выпечка',
  'dishType.dessert': 'Десерт',
  'dishType.side-dish': 'Гарнир',
  'dishType.other': 'Другое',
  'sort.relevance': 'По релевантности',
  'sort.name': 'По имени',
  'sort.recent-added': 'Недавно добавленные',
  'sort.recent-edited': 'Недавно изменённые',
  'sort.shortest-time': 'Самое быстрое',
  'group.none': 'Нет',
  'group.kind': 'Тип элемента',
  'group.dish-type': 'Основной тип блюда',
  'kind.recipe': 'Рецепт',
  'kind.simpleFood': 'Простое блюдо',
  'kind.recipes': 'Рецепты',
  'kind.simpleFoods': 'Простые блюда',
  'catalog.group.other': 'Другое',
  'catalog.group.unclassified': 'Без типа',
  'catalog.group.results': 'Результаты',
  'catalog.group.pairings': 'Хорошо сочетается',
  'catalog.group.fromFavorites': 'Из избранного',
  'catalog.group.suitable': 'Подходит',
  'catalog.group.allItems': 'Все позиции',
  'catalog.group.suggested': 'Рекомендации',
  'catalog.leftovers': 'Остатки',
  'catalog.leftoversThisWeek': 'Остаток на эту неделю',
  'catalog.remainingBadge': 'Остаток',
  'catalog.searchPlaceholder': 'Поиск блюд, тегов…',
  'catalog.sortBy': 'Сортировка',
  'catalog.groupBy': 'Группировка',
  'catalog.filters': 'Фильтры',
  'catalog.clearFilters': 'Сбросить фильтры',
  'catalog.hasIngredient': 'Есть {name}',
  'catalog.withoutIngredient': 'Без {name}',
  'catalog.maxTimeChip': '≤ {minutes} мин',
  'catalog.filtersCount': 'Фильтры ({count})',
  'catalog.removeFilter': 'Убрать фильтр {label}',
  'filter.type': 'Тип',
  'filter.occasion': 'Приём пищи',
  'filter.role': 'Роль в приёме',
  'filter.effort': 'Сложность',
  'filter.advanced': 'Дополнительно',
  'filter.ingredients': 'Ингредиенты',
  'filter.maxTime': 'Максимальное общее время (минуты)',
  'filter.maxTimeHelp':
    'Только рецепты с записанным общим временем. Отсутствие времени не считается нулём.',
  'filter.containsIngredient': 'Содержит ингредиент',
  'filter.excludeIngredient': 'Исключить ингредиент',
  'filter.pickCatalog': 'Выбрать из каталога',
  'filter.ingredientDisclaimer':
    'Фильтры смотрят только на связанные ингредиенты каталога. Несвязанные импортированные строки игнорируются. Это не гарантия безопасности при аллергии.',
  'filter.tags': 'Домашние теги',
  'cleanup.missing-occasion': 'Нет приёма пищи',
  'cleanup.missing-dish-type': 'Нет типа блюда',
  'cleanup.missing-time': 'Нет записанного времени',
  'cleanup.unlinked-ingredients': 'Несвязанные строки ингредиентов',
  'cleanup.label': 'Наведение порядка',
  'cleanup.findGaps': 'Найти пробелы',
  'cleanup.help': 'Найти необязательные пробелы в каталоге. Пропуски — не ошибки.',
  'cleanup.alertTitle': 'Наведение порядка в каталоге',
  'cleanup.alertBody':
    'Показаны позиции, где этот необязательный признак пуст. Они по-прежнему работают в плане и списках покупок.',
  'catalog.staleFiltersTitle': 'Некоторые фильтры больше не в каталоге',
  'catalog.staleFiltersBody':
    'Архивные теги по-прежнему применяются по имени. Удалённые теги и отсутствующие ингредиенты остаются чипами, чтобы их можно было снять; при поиске они игнорируются, чтобы вид не опустошал библиотеку.',
  'section.produce': 'Овощи и фрукты',
  'section.bakery': 'Выпечка',
  'section.chilled': 'Холодильник',
  'section.pantry': 'Кладовая',
  'section.frozen': 'Морозилка',
  'section.other': 'Другое',
  'section.label': 'Отдел магазина',
  'section.placeholder': 'Нет — показывается в «Другое»',
  'unitFamily.volume': 'Объём',
  'unitFamily.mass': 'Масса',
  'unitFamily.count': 'Штуки',
  'unitFamily.current': 'Текущая',
  'unit.g': 'Грамм (г)',
  'unit.kg': 'Килограмм (кг)',
  'unit.oz-mass': 'Унция, вес (oz)',
  'unit.ml': 'Миллилитр (мл)',
  'unit.l': 'Литр (л)',
  'unit.tsp': 'Чайная ложка (ч. л.)',
  'unit.tbsp': 'Столовая ложка (ст. л.)',
  'unit.cup': 'Чашка (старая — без соглашения)',
  'unit.cup-us': 'Чашка, США (240 мл)',
  'unit.cup-metric': 'Чашка, метрическая (250 мл)',
  'unit.oz-fl': 'Унция жидкая (fl oz)',
  'unit.piece': 'Штука',
  'unit.serving': 'Порция',
  'unitShort.g': 'г',
  'unitShort.kg': 'кг',
  'unitShort.oz-mass': 'унция',
  'unitShort.ml': 'мл',
  'unitShort.l': 'л',
  'unitShort.tsp': 'ч. л.',
  'unitShort.tbsp': 'ст. л.',
  'unitShort.cup': 'чашка',
  'unitShort.cup-us': 'чашка',
  'unitShort.cup-metric': 'чашка',
  'unitShort.oz-fl': 'ж. унция',
  'unitShort.piece': 'шт.',
  'unitShort.serving': 'порц.',
  'lists.title': 'Покупки',
  'lists.loading': 'Загрузка списков…',
  'lists.current': 'Текущие',
  'lists.history': 'История',
  'lists.help':
    'Создайте список из Плана и отмечайте покупки. Правки плана не перезаписывают список сами — используйте «Обновить по плану».',
  'lists.updated': 'Обновлён {when}',
  'lists.goToPlan': 'К плану',
  'lists.status.open': 'открыт',
  'lists.status.closed': 'закрыт',
  'grocery.loading': 'Загрузка списка…',
  'grocery.notFound': 'Этот список покупок не найден.',
  'grocery.deleteItemTitle': 'Удалить позицию',
  'grocery.deleteItemBody': 'Убрать «{name}» из списка?',
  'grocery.closeTitle': 'Закрыть список',
  'grocery.closeBody':
    'Закрытый список нельзя править или обновлять из плана. Позже его можно открыть снова.',
  'grocery.closeConfirm': 'Закрыть список',
  'grocery.deleteListTitle': 'Удалить список',
  'grocery.deleteListBody': 'Удалить «{name}» и все позиции? Это нельзя отменить.',
  'grocery.deleteListConfirm': 'Удалить список',
  'grocery.checkItem': 'Отметить {name}',
  'grocery.usedBy': 'Используется в {name}',
  'grocery.editItem': 'Изменить {name}',
  'grocery.deleteNamed': 'Удалить {name}',
  'grocery.checkAll': 'Отметить все {name}',
  'grocery.hideChecked': 'Скрыть отмеченные',
  'grocery.addItem': 'Добавить позицию',
  'grocery.addToList': 'Добавить в список',
  'grocery.reopen': 'Открыть снова',
  'grocery.grouped': 'По отделам',
  'grocery.flat': 'Списком',
  'grocery.close': 'Закрыть',
  'grocery.noItems': 'Пока нет позиций.',
  'grocery.allChecked': 'Все позиции отмечены.',
  'grocery.saveFailed': 'Не удалось сохранить ({error})',
  'grocery.listNotFoundTitle': 'Список не найден',
  'grocery.usedByHeading': 'Для чего',
  'grocery.sourceMissing': 'Этого приёма пищи уже нет в плане.',
  'grocery.noSources': 'Список создан до сохранения вкладов приёмов пищи.',
  'grocery.error.reopen': 'Не удалось открыть снова ({error})',
  'grocery.error.close': 'Не удалось закрыть ({error})',
  'grocery.error.delete': 'Не удалось удалить ({error})',
  'grocery.error.updateItem': 'Не удалось обновить позицию ({error})',
  'grocery.error.addItem': 'Не удалось добавить позицию ({error})',
  'recipes.title': 'Рецепты',
  'recipes.import': 'Импорт рецепта',
  'recipes.new': 'Новый рецепт',
  'recipes.simpleFoods': 'Простые блюда',
  'recipes.ingredients': 'Ингредиенты',
  'recipes.tags': 'Теги',
  'recipes.select': 'Выбрать',
  'recipes.done': 'Готово',
  'recipes.clearSelection': 'Сбросить',
  'recipes.selectVisible': 'Выбрать видимые',
  'recipes.addTags': 'Добавить теги',
  'recipes.removeTags': 'Убрать теги',
  'recipes.removeTag': 'Убрать тег',
  'recipes.manageSimpleFoods': 'Простые блюда',
  'recipes.updateTags': 'Обновить теги',
  'recipes.updateTagsBody': 'Применить изменения тегов к выбранным рецептам и простым блюдам?',
  'recipes.applyTo': 'Применить к {count}',
  'recipes.addClause': '. Добавить: {names}',
  'recipes.removeClause': '. Убрать: {names}',
  'recipes.yieldEffort': '{yield} · {effort}',
  'recipes.yieldEffortTime': '{yield} · {effort} · {minutes} мин',
  'recipes.tagsUpdated': 'Теги обновлены',
  'recipes.tagsOnSelection': 'Теги выбранных позиций',
  'recipes.tagPlaceholder': 'Введите тег и нажмите Enter',
  'recipes.yield': 'Выход {quantity}',
  'view.error.emptyName': 'Название вида не может быть пустым',
  'view.error.nameCollision': 'Другой вид уже называется так',
  'view.error.notFound': 'Сохранённый вид не найден',
  'view.saved': 'Сохранено «{name}»',
  'view.updated': 'Вид обновлён',
  'view.renamed': 'Вид переименован',
  'view.deleted': 'Вид удалён',
  'tags.error.emptySelection': 'Выберите хотя бы одну позицию',
  'tags.error.emptyName': 'Название тега не может быть пустым',
  'tags.error.emptyOp': 'Выберите теги для добавления или удаления',
  'library.savedView': 'Сохранённый вид',
  'library.unsaved': 'Есть несохранённые изменения',
  'library.updateView': 'Обновить вид',
  'library.saveAsNew': 'Сохранить как новый',
  'library.deleteView': 'Удалить вид',
  'library.deleteViewTitle': 'Удалить «{name}»?',
  'library.deleteViewBody': 'Удаляется только сохранённый вид. Рецепты и текущие фильтры остаются.',
  'library.renameView': 'Переименовать вид',
  'library.saveAsNewTitle': 'Сохранить как новый вид',
  'library.viewNamePlaceholder': 'Обеды детям',
  'library.unsavedSuffix': '{name} (не сохранён)',
  'picker.leftoverBatch': 'Из заготовки {weekday}',
  'picker.pairedWith': 'Часто вместе с {name}',
  'picker.pairedTogether': 'Часто готовят вместе',
  'picker.fromFavoriteNamed': 'Из избранного {name}',
  'picker.fromFavorite': 'Из избранного',
  'picker.alreadyPlanned': 'Уже в плане на эту неделю',
  'picker.sameDayIneligible': 'Только в день готовки — приготовлено {date}',
  'picker.sourceQuestion': 'Откуда взять этот компонент?',
  'picker.cookNew': 'Готовить новое (эта заготовка)',
  'picker.cookNewHint': 'Приготовить свежую порцию для этого приёма пищи.',
  'picker.useExisting': 'Взять существующую заготовку в этом плане',
  'picker.useExistingHint': 'Использовать остаток заготовки, приготовленной на этой неделе.',
  'picker.allocated': 'На этот приём пищи',
  'picker.totalOutput': 'Всего выход заготовки',
  'picker.prepDate': 'Дата заготовки',
  'picker.choosePrep': 'Выберите заготовку с остатком:',
  'picker.selectPrep': 'Выберите заготовку.',
  'picker.noEligiblePrep': 'В этом плане нет подходящей заготовки с остатком.',
  'picker.cookNewTitle': 'Готовить новое — {name}',
  'picker.useExistingTitle': 'Существующая — {name}',
  'picker.pairedBadge': 'В паре',
  'picker.favoriteBadge': 'Избранное',
  'error.overAllocated': 'Это больше запланированного выхода заготовки.',
  'error.reuseForbidden': 'Этот рецепт нельзя использовать повторно в тот день.',
  'error.beforePrep': 'Нельзя использовать заготовку до дня готовки.',
  'error.incompatibleQuantity': 'Единицы количества несовместимы.',
  'error.invalidQuantity': 'Введите положительное количество.',
  'error.favoriteMissing': 'В избранном нет такого рецепта или простого блюда.',
  'error.planGeneric': 'Не удалось обновить ({error})',
  'error.addComponent': 'Не удалось добавить компонент ({error})',
  'error.clearSlot': 'Не удалось очистить слот',
  'error.excludeSlot': 'Не удалось исключить слот',
  'import.error.empty': 'Вставьте JSON-LD или выберите файл.',
  'import.error.urlOnly': 'Мы не загружаем сайты — вставьте JSON-LD или HTML с ним.',
  'import.error.parseFailed': 'Не удалось разобрать как JSON или HTML с JSON-LD.',
  'import.error.noRecipe': 'Рецепт Schema.org не найден.',
  'import.error.generic': 'Импорт не удался ({error})',
  'import.title': 'Импорт рецепта',
  'import.help':
    'Вставьте Schema.org JSON-LD или HTML с application/ld+json. Мы не загружаем URL. После извлечения всё подтверждается в обычном редакторе.',
  'import.pasteLabel': 'Вставить JSON-LD или HTML',
  'import.dropFile': 'Перетащите файл сюда',
  'import.chooseFile': 'Выбрать файл',
  'import.extract': 'Извлечь',
  'import.failedTitle': 'Не удалось импортировать',
  'import.pickOne': 'Найдено несколько рецептов — выберите один',
  'import.readFailed': 'Не удалось прочитать файл',
  'import.badFileType': 'Нужен файл .json, .jsonld или .html',
  'prompt.warningTitle': 'Подсказка по плану',
  'prompt.infoTitle': 'Совет',
  'prompt.maxUnits': 'нагрузка заготовки ({units}) выше максимума единиц ({max}).',
  'prompt.demanding': 'несколько сложных заготовок в этот день.',
  'prompt.quickOnly': 'небыстрая заготовка в день только быстрых блюд.',
  'prompt.preferredPrep': 'заготовка вне предпочтительных дней.',
  'prompt.vegetables': 'Добавить овощи?',
  'prompt.breakfastRepeat': 'Одинаковый завтрак повторяется в этом плане.',
  'prompt.identicalDinners': 'Одинаковые ужины в соседние дни ({a} и {b}).',
  'prompt.previousWeek': 'Было на прошлой неделе — рассмотрите другое: {names}.',
  'editor.newRecipe': 'Новый рецепт',
  'editor.editRecipe': 'Изменить рецепт',
  'editor.importConfirmTitle': 'Импортировано — проверьте',
  'editor.amountPlusUnit': 'Количество + единица',
  'editor.ingredient': 'Ингредиент',
  'editor.organization': 'Организация',
  'editor.roles': 'Роли',
  'editor.rolesHelp':
    '«Полное» значит, что блюдо можно планировать отдельно и оно подходит для автозаполнения.',
  'editor.mealTypes': 'Приёмы пищи',
  'editor.dishType': 'Основной тип блюда',
  'editor.cuisine': 'Кухня',
  'editor.tags': 'Теги',
  'editor.tagsHelp':
    'Выберите существующий тег или введите новый. Архивные теги остаются назначенными, но не предлагаются.',
  'editor.effort': 'Сложность',
  'editor.reuse': 'Повторное использование',
  'editor.activeTime': 'Активное время (минуты)',
  'editor.totalTime': 'Общее время (минуты)',
  'editor.freezer': 'Можно заморозить',
  'editor.freezingNotes': 'Заметки о заморозке и разогреве',
  'editor.sourceUrl': 'URL источника',
  'editor.maxRepeats': 'Максимум повторов в плане',
  'editor.ingredients': 'Ингредиенты',
  'editor.removeIngredient': 'Удалить ингредиент',
  'editor.amountMode': 'Количество',
  'editor.describeAmount': 'Описать количество',
  'editor.quantityText': 'например по вкусу, щепотка',
  'editor.note': 'Примечание',
  'editor.noteOptional': 'необязательно',
  'editor.instructions': 'Инструкции',
  'editor.notes': 'Заметки',
  'editor.photoUrl': 'URL фото',
  'editor.photoHelp': 'ссылка http(s) на изображение',
  'editor.yield': 'Выход',
  'editor.portion': 'Порция',
  'editor.invalidYield': 'Выход и порция должны быть корректными количествами',
  'editor.yieldPositive': 'Выход должен быть больше нуля',
  'editor.yieldAmount': 'Выход',
  'editor.yieldUnit': 'Единица выхода',
  'editor.portionAmount': 'Порция на человека',
  'editor.portionUnit': 'Единица порции',
  'editor.resolveNameFailed': 'Не удалось сопоставить название ингредиента',
  'editor.saved': 'Рецепт сохранён',
  'editor.saveFailed': 'Не удалось сохранить рецепт',
  'editor.saveFailedDetail': 'Не удалось сохранить рецепт ({error})',
  'editor.invalidPhotoUrl': 'URL фото должен начинаться с http:// или https://',
  'import.matched': 'Сопоставлено: {name}',
  'import.catalogIngredient': 'ингредиент каталога',
  'import.unlink': 'Отвязать',
  'import.unlinkedOk': 'Не связано — сохранение разрешено.',
  'import.chooseMatch': 'Выбрать из каталога',
  'import.original': 'Исходная строка: {text}',
  'import.keepUnspecified': 'Оставить без уточнения',
  'import.usCup': 'Чашка США',
  'import.metricCup': 'Метрическая чашка',
  'import.unspecifiedOz': 'Без уточнения',
  'import.weightOz': 'Вес (унция)',
  'import.fluidOz': 'Жидкость (ж. унция)',
  'import.leaveUnresolved': 'Оставить неразрешённым',
  'candidate.title': 'Какой ингредиент вы имели в виду?',
  'candidate.body':
    '«{name}» совпадает с несколькими ингредиентами. Выберите один, создайте новый или оставьте строку несвязанной.',
  'candidate.create': 'Создать новый ингредиент «{name}»',
  'candidate.leaveUnlinked': 'Оставить несвязанным',
  'alias.title': 'Добавить это имя в каталог?',
  'alias.body':
    '«{phrase}» ещё не имя и не синоним {label}. Синоним поможет будущим импортам. Связь только в этом рецепте каталог не меняет.',
  'alias.add': 'Добавить «{phrase}» как синоним',
  'alias.linkOnly': 'Связать только этот рецепт',
  'ingredientName.placeholder': 'например курица',
  'ingredientName.empty': 'Ингредиентов нет — введите имя, чтобы создать.',
  'ingredientName.create': 'Создать новый ингредиент «{query}»',
  'detail.loading': 'Загрузка…',
  'detail.recipeNotFound': 'Рецепт не найден.',
  'detail.foodNotFound': 'Простое блюдо не найдено.',
  'detail.deleteRecipe': 'Удалить рецепт',
  'detail.deleteRecipeBody':
    'Удалить «{name}»? Это нельзя отменить в приложении (нужен резервный файл).',
  'detail.recipeDeleted': 'Рецепт удалён',
  'detail.recipeNotFoundTitle': 'Рецепт не найден',
  'detail.recipeNotFoundShort': 'Рецепт не найден.',
  'detail.yieldPortion': 'Выход {yield} · порция {portion} / чел.',
  'detail.effortReuse': '{effort} · {reuse}',
  'detail.freezerSuffix': ' · Можно заморозить',
  'detail.activeMin': 'Активно {minutes} мин',
  'detail.totalMin': 'Всего {minutes} мин',
  'detail.scale': 'Просмотр масштаба',
  'detail.scaleHelp': 'Только просмотр — сохранённый рецепт не меняется. Единица: {unit}.',
  'detail.scaleTo': 'Масштаб до ({unit})',
  'detail.scaleFactor': 'Коэффициент ×{factor}',
  'detail.noIngredients': 'Ингредиенты не указаны.',
  'detail.noInstructions': 'Инструкций пока нет.',
  'detail.freezingNotes': 'Заметки о заморозке',
  'detail.pairsWell': 'Хорошо сочетается с',
  'detail.noPairings': 'Сочетаний пока нет.',
  'detail.pairingOption': '{kind} · {name}',
  'detail.alreadyPaired': 'Уже в сочетаниях',
  'detail.selfPairing': 'Нельзя сочетать рецепт с самим собой',
  'detail.pairingFailed': 'Не удалось добавить сочетание',
  'detail.pairingAdded': 'Сочетание добавлено',
  'detail.removePairingFailed': 'Не удалось убрать сочетание',
  'detail.source': 'Источник: {url}',
  'detail.pairings': 'Сочетания',
  'detail.addPairing': 'Добавить сочетание…',
  'detail.removePairing': 'Убрать сочетание',
  'detail.edit': 'Изменить',
  'foods.title': 'Простые блюда',
  'foods.help': 'Быстрые позиции для плана без полного рецепта.',
  'foods.helpLong':
    'То, что подают без рецепта (хлеб, йогурт, банан). Отключите, чтобы не предлагать отдельно — как ингредиенты они остаются.',
  'foods.defaultPortion': 'Порция по умолчанию',
  'foods.defaultQty': 'По умолчанию {quantity}',
  'foods.createFailed': 'Не удалось создать простое блюдо ({error})',
  'foods.deleteBodyLong':
    'Удалить «{name}» как отдельное предложение? Ингредиент в каталоге останется.',
  'foods.empty': 'Простых блюд пока нет.',
  'foods.deleteNamed': 'Удалить {name}',
  'foods.badge': 'Простое блюдо',
  'foods.notFoundTitle': 'Простое блюдо не найдено',
  'foods.ingredientLine': 'Ингредиент: {name} · По умолчанию {quantity}',
  'validation.nameRequired': 'Нужно название',
  'validation.portionPositive': 'Порция должна быть больше нуля',
  'foods.namePlaceholder': 'например йогурт',
  'foods.includeSuggestions': 'Включать в предложения блюд',
  'foods.add': 'Добавить простое блюдо',
  'foods.added': 'Простое блюдо добавлено',
  'foods.deleted': 'Простое блюдо удалено',
  'foods.notFound': 'Простое блюдо не найдено',
  'foods.deleteTitle': 'Удалить простое блюдо',
  'foods.deleteBody': 'Удалить «{name}»?',
  'foods.includeInSuggestions': 'Включать в предложения',
  'ingredients.title': 'Ингредиенты',
  'ingredients.help': 'Имена каталога, синонимы и то, отмечается ли позиция на новых списках.',
  'ingredients.helpShort':
    'Канонические имена и синонимы. Сохранение рецепта тоже создаёт ингредиенты из введённых имён.',
  'ingredients.empty': 'Ингредиентов пока нет.',
  'ingredients.nameCollision': 'Ингредиент с таким именем или синонимом уже есть',
  'ingredients.aliasesList': 'Синонимы: {list}',
  'ingredients.add': 'Добавить ингредиент',
  'ingredients.added': 'Ингредиент добавлен',
  'ingredients.deleted': 'Ингредиент удалён',
  'ingredients.notFound': 'Ингредиент не найден',
  'ingredients.deleteTitle': 'Удалить ингредиент',
  'ingredients.deleteBody': 'Удалить «{name}»? Строки в рецептах сохранятся.',
  'ingredients.aliases': 'Синонимы',
  'ingredients.category': 'Категория',
  'ingredients.preferredLabel': 'Предпочтительное имя ({locale})',
  'ingredients.aliasesLocale': 'Синонимы ({locale})',
  'ingredients.defaultName': 'Использовать имя по умолчанию',
  'ingredients.collapse': 'Свернуть редактирование',
  'ingredients.editNamed': 'Изменить {name}',
  'ingredients.deleteNamed': 'Удалить {name}',
  'tags.title': 'Теги',
  'tags.usedBy': 'Используется: {count}',
  'tags.renamed': 'Тег переименован',
  'tags.notFound': 'Тег не найден',
  'tags.archivedNotice': 'Тег в архиве',
  'tags.restored': 'Тег снова в подсказках',
  'tags.mergeTitle': 'Объединить теги',
  'tags.mergeBody':
    'Объединить «{source}» в «{target}»? В живых рецептах и простых блюдах останется только «{target}». Подписи прошлых заготовок не меняются.',
  'tags.merge': 'Объединить',
  'tags.mergeInto': 'Объединить с…',
  'tags.mergeNamed': 'Объединить {name} с другим тегом',
  'tags.renameNamed': 'Переименовать {name}',
  'tags.mergedInto': 'Объединено в «{name}»',
  'tags.sameTag': 'Выберите другой тег',
  'tags.deleteTitle': 'Удалить «{name}»?',
  'tags.deleteBody':
    'Тег стоит на {recipes} и {foods}. Удалится только тег — блюда останутся. Подписи прошлых заготовок не меняются.',
  'tags.deleteConfirm': 'Удалить тег',
  'tags.deleted': 'Тег удалён',
  'tags.archive': 'В архив',
  'tags.restore': 'Восстановить',
  'tags.emptyName': 'Название тега не может быть пустым',
  'tags.nameCollision': 'Другой тег уже называется так',
  'tags.help':
    'Домашние подписи для рецептов и простых блюд. Переименуйте, архивируйте, объединяйте или удаляйте тег — блюда не удаляются. История плана показывает имя на момент готовки.',
  'tags.empty': 'Тегов пока нет. Добавьте при редактировании рецепта или простого блюда.',
  'tags.archivedSuffix': '{name} (в архиве)',
  'tags.archived': 'В архиве',
  'meal.overAllocTitle': 'Не хватает выхода заготовки',
  'meal.overAllocBody': 'Это больше запланированного выхода. Выберите, как продолжить:',
  'meal.increaseOutput': 'Увеличить количество готовки',
  'meal.reduceAlloc': 'Уменьшить это распределение',
  'meal.createAnother': 'Создать ещё одну заготовку',
  'meal.saveFavorite': 'Сохранить как избранное',
  'meal.favoriteName': 'Название избранного',
  'meal.favoriteNeedComponents': 'Добавьте компоненты перед сохранением избранного',
  'meal.deleteFavorite': 'Удалить избранное',
  'meal.deleteFavoriteBody': 'Удалить избранное «{name}»?',
  'meal.removeComponent': 'Убрать компонент',
  'meal.removeComponentBody': 'Убрать этот компонент из приёма пищи?',
  'meal.sharedPrep': 'Общая заготовка',
  'meal.editAllocation': 'Изменить распределение',
  'meal.editPrep': 'Изменить заготовку',
  'meal.removeComponentAria': 'Убрать компонент',
  'meal.deleteFavoriteAria': 'Удалить {name}',
  'meal.favorites': 'Избранное',
  'meal.unallocatedPrep': 'Нераспределённая заготовка',
  'meal.unallocatedLine': '{name}: {quantity} не распределено',
  'meal.prepLine': ' · заготовка {date} ({quantity} всего)',
  'meal.addComponent': '+ Компонент',
  'meal.moreActions': 'Другие действия',
  'meal.insertFavorite': 'Вставить избранное',
  'meal.noComponents': 'Компонентов пока нет. Добавьте рецепт или простое блюдо.',
  'meal.noFavorites': 'Избранного пока нет.',
  'meal.alsoSupplies': 'Эта заготовка также нужна для:',
  'meal.removeThisOnly': 'Убрать только из этого приёма',
  'meal.removeAllAffected': 'Убрать из всех затронутых приёмов',
  'meal.removeNamedBody': 'Убрать {name} из этого приёма?',
  'meal.cannotUndo': 'Это нельзя отменить.',
  'meal.duplicateName': 'Избранное с таким именем уже есть',
  'meal.emptyName': 'Введите название',
  'meal.saveFavoriteFailed': 'Не удалось сохранить избранное',
  'meal.favoriteSaved': 'Избранное сохранено',
  'meal.inserted': 'Вставлено «{name}»',
  'meal.missingRef': 'В избранном нет позиции ({label})',
  'meal.deleteFavoriteFailed': 'Не удалось удалить избранное',
  'meal.editPreparation': 'Изменить заготовку',
  'meal.slotTitle': '{meal} · {date}',
  'confirm.clearMeal': 'Очистить приём пищи',
  'confirm.clearMealBody': 'Убрать все компоненты из этого приёма?',
  'confirm.clearSharedTitle': 'Очистить приём с общей заготовкой',
  'confirm.clearSharedBody': 'Этот приём использует заготовку, которая кормит и другие приёмы:',
  'confirm.clearThisOnly': 'Очистить только этот приём',
  'confirm.removeSharedAll': 'Убрать общую заготовку из всех приёмов',
  'confirm.excludeMeal': 'Исключить приём',
  'confirm.excludeMealBody':
    'Пометить приём как исключённый / едим вне дома? Компоненты будут удалены.',
  'confirm.excludeSharedTitle': 'Исключить приём с общей заготовкой',
  'confirm.excludeSharedBody': 'Исключение очищает этот приём. Общая заготовка также нужна для:',
  'confirm.excludeThisOnly': 'Исключить только этот приём',
  'confirm.removeSharedAndExclude': 'Убрать общую заготовку из всех приёмов и исключить',
  'confirm.exclude': 'Исключить',
} as const satisfies Record<MessageId, string>

export const ruPlurals = {
  'filter.showItems': {
    one: 'Показать {count} позицию',
    few: 'Показать {count} позиции',
    many: 'Показать {count} позиций',
    other: 'Показать {count} позиции',
  },
  'catalog.selected': {
    one: 'Выбрана {count} позиция',
    few: 'Выбрано {count} позиции',
    many: 'Выбрано {count} позиций',
    other: 'Выбрано {count} позиции',
  },
  'catalog.itemCount': {
    one: '{count} позиция',
    few: '{count} позиции',
    many: '{count} позиций',
    other: '{count} позиции',
  },
  'import.ingredientLines': {
    one: '{count} строка ингредиентов',
    few: '{count} строки ингредиентов',
    many: '{count} строк ингредиентов',
    other: '{count} строки ингредиентов',
  },
  'tags.recipeCount': {
    one: '{count} рецепте',
    few: '{count} рецептах',
    many: '{count} рецептах',
    other: '{count} рецептах',
  },
  'tags.foodCount': {
    one: '{count} простом блюде',
    few: '{count} простых блюдах',
    many: '{count} простых блюдах',
    other: '{count} простых блюдах',
  },
} as const satisfies Record<PluralId, PluralForms>
